# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    ipaddress=$(curl -s http://ipinfo.io/ip)
    echo $ipaddress
    echo "##vso[task.setvariable variable=address;isOutput=true;]$ipaddress"
    echo $address
    npm i express --save
    node index.js & sleep 30s || kill $!
  displayName: 'npm install express'
